### PR TITLE
updates

### PR DESCRIPTION
**Pull request by Thesocialseo**
Updates
[html5-boilerplate_v7.3.0.zip](https://github.com/Thesocialseo/pnptube/files/4726367/html5-boilerplate_v7.3.0.zip)

### CODE REVIEW

**Comment by Thesocialseo** [comment]
launch

**Comment by GetWithTheProgram** [comment]
Spunfun n lost here. Reddit is spunpunt

**Comment by GetWithTheProgram** [comment]
I don't code idk wtf this is I'm just spun

**Comment by GetWithTheProgram** [comment]
Looool

**Review by GetWithTheProgram — COMMENTED** [review]
Looks good I too do the coding.

**Pull request merged**
